#!/bin/bash
php imdb2mpeg.php "Austin Powers International Man of Mystery"
php imdb2mpeg.php "Austin Powers The Spy Who Shagged Me"
php imdb2mpeg.php "Austin Powers in Goldmember"
php imdb2mpeg.php "Behind Enemy Lines"
php imdb2mpeg.php "Black Hawk Down"
php imdb2mpeg.php "Charlies Angels Full Throttle"
php imdb2mpeg.php "Doomsday"
php imdb2mpeg.php "Ghost Rider"
php imdb2mpeg.php "Hancock"
php imdb2mpeg.php "Hellboy II The Golden Army"
php imdb2mpeg.php "Hidalgo"
php imdb2mpeg.php "Indiana Jones and the Kingdom of the Crystal Skull"
php imdb2mpeg.php "Iron Man"
php imdb2mpeg.php "Journey to the Center of the Earth"
php imdb2mpeg.php "Jumper"
php imdb2mpeg.php "Street Kings"
php imdb2mpeg.php "The Dark Knight"
php imdb2mpeg.php "The Day After Tomorrow"
php imdb2mpeg.php "The Forbidden Kingdom"
php imdb2mpeg.php "The Incredible Hulk"
php imdb2mpeg.php "The Mummy Tomb of the Dragon Emperor"
php imdb2mpeg.php "The Transporter"
php imdb2mpeg.php "Transporter 2"
php imdb2mpeg.php "10000 BC"
php imdb2mpeg.php "Dogma"
php imdb2mpeg.php "Harold and Kumar Escape from Guantanamo Bay"
php imdb2mpeg.php "Nims Island"
php imdb2mpeg.php "The Beach"
php imdb2mpeg.php "The Bucket List"
php imdb2mpeg.php "The Golden Compass"
php imdb2mpeg.php "Film Noir"
php imdb2mpeg.php "Ratatouille"
php imdb2mpeg.php "Team America World Police"
php imdb2mpeg.php "Ali"
php imdb2mpeg.php "About Schmidt"
php imdb2mpeg.php "Being John Malkovich"
php imdb2mpeg.php "Burn After Reading"
php imdb2mpeg.php "George Carlin Its Bad for Ya!"
php imdb2mpeg.php "Just Married"
php imdb2mpeg.php "Leatherheads"
php imdb2mpeg.php "Michael McIntyre Live and Laughing"
php imdb2mpeg.php "Strictly Ballroom"
php imdb2mpeg.php "Deception"
php imdb2mpeg.php "Firewall"
php imdb2mpeg.php "Memento"
php imdb2mpeg.php "Shooters"
php imdb2mpeg.php "Sweeney Todd The Demon Barber of Fleet Street"
php imdb2mpeg.php "The Bank Job"
php imdb2mpeg.php "Untraceable"
php imdb2mpeg.php "21"
php imdb2mpeg.php "August Rush"
php imdb2mpeg.php "Death Defying Acts"
php imdb2mpeg.php "Pandora and the Flying Dutchman"
php imdb2mpeg.php "The Duchess"
php imdb2mpeg.php "Unfaithful"
php imdb2mpeg.php "American Psycho"
php imdb2mpeg.php "My Little Eye"
php imdb2mpeg.php "Rabid"
php imdb2mpeg.php "Vanilla Sky"
php imdb2mpeg.php "Girl Interrupted"
php imdb2mpeg.php "Mr and Mrs Smith"
php imdb2mpeg.php "Wallace and Gromit A Grand Day Out"
php imdb2mpeg.php "Wallace and Gromit A Matter of Load or Death"
php imdb2mpeg.php "Wallace and Gromit The Curse Of The Rabbit"
php imdb2mpeg.php "Windtalkers"
php imdb2mpeg.php "WALL-E"
php imdb2mpeg.php "The Other Boleyn Girl"
php imdb2mpeg.php "Vantage Point"
php imdb2mpeg.php "Chicago 10"
php imdb2mpeg.php "What Lies Beneath"
php imdb2mpeg.php "JCVD"
php imdb2mpeg.php "One Fine Day"
php imdb2mpeg.php "Batman"
php imdb2mpeg.php "Batman Forever"
php imdb2mpeg.php "Batman Returns"
php imdb2mpeg.php "Batman and Robin"
php imdb2mpeg.php "Gallipoli"
php imdb2mpeg.php "Independence Day"
php imdb2mpeg.php "xXx The Next Level"
php imdb2mpeg.php "The Waiting Room" 0902348
php imdb2mpeg.php "Herbie Fully Loaded"
php imdb2mpeg.php "Hero"
php imdb2mpeg.php "American Pie 2"
php imdb2mpeg.php "American Wedding"
php imdb2mpeg.php "Shrek The Halls"
php imdb2mpeg.php "Shrek"
php imdb2mpeg.php "Shrek 2"
php imdb2mpeg.php "Blindness"
php imdb2mpeg.php "Body of Lies"
php imdb2mpeg.php "Brideshead Revisited" 0412536
php imdb2mpeg.php "Hounddog"
php imdb2mpeg.php "Outlander"
php imdb2mpeg.php "Permanent Vacation" 0475431
php imdb2mpeg.php "The Escapist"
php imdb2mpeg.php "The X Files I Want To Believe"
php imdb2mpeg.php "Zack and Miri Make A"
php imdb2mpeg.php "City of Ember"
php imdb2mpeg.php "Death Proof"
php imdb2mpeg.php "Death Race"
php imdb2mpeg.php "Napoleon Dynamite"
php imdb2mpeg.php "Cliffhanger"
php imdb2mpeg.php "Elephants Dream"
php imdb2mpeg.php "The Mummy"
php imdb2mpeg.php "The Mummy Returns"
php imdb2mpeg.php "The Worlds Fastest Indian"
php imdb2mpeg.php "Lara Croft Tomb Raider The Cradle of Life"
php imdb2mpeg.php "You've Got Mail"
php imdb2mpeg.php "Star Trek Nemesis" 0253754
php imdb2mpeg.php "School of Rock"
php imdb2mpeg.php "The Naked Gun 2"
php imdb2mpeg.php "A Life Less Ordinary"
php imdb2mpeg.php "A River Runs Through It"
php imdb2mpeg.php "Arlington Road"
php imdb2mpeg.php "Back to the Future Part II"
php imdb2mpeg.php "Changeling"
php imdb2mpeg.php "Crank"
php imdb2mpeg.php "Seven Pounds"
php imdb2mpeg.php "The Butterfly Effect"
php imdb2mpeg.php "Transporter 3"
php imdb2mpeg.php "Flash of Genius"
php imdb2mpeg.php "God on Trial"
php imdb2mpeg.php "Incendiary"
php imdb2mpeg.php "Thick as Thieves"
php imdb2mpeg.php "Twilight"
php imdb2mpeg.php "Viva" 0393956
php imdb2mpeg.php "Star Wars Holiday Special"
php imdb2mpeg.php "Bear Island"
php imdb2mpeg.php "Brokeback Mountain"
php imdb2mpeg.php "Alive"
php imdb2mpeg.php "Amélie"

# Not yet done
php imdb2mpeg.php "American Pie"



# BMW Shorts - Season 1
#php imdb2mpeg.php "Ambush" 0283875
#php imdb2mpeg.php "Chosen" 0283994
#php imdb2mpeg.php "The Follow" 0283994
#php imdb2mpeg.php "Star" 0286151
#php imdb2mpeg.php "Powder Keg"
# BMW Shorts - Season 2
#php imdb2mpeg.php "Hostage" 0338111
#php imdb2mpeg.php "Ticker" 0340398

